package org.websigni.piglets.riskestimator

// IMPORTS
import org.apache.log4j.Logger
import org.apache.commons.lang.ObjectUtils;

// DECLARATIONS
declare Candidate
    name : String
    surname : String
    age : int
    nationality : String
    familyStatus : String
end

declare RiskEstimation
    riskPoints : int
    riskLevel : String
end

// RULES
rule "Risky name"
    when
        Candidate( name.hashCode() % 2 == 0 )
        $re : RiskEstimation ( $p : riskPoints )
        $log : Logger()
    then
    	$log.info("Risky name");
        $re.setRiskPoints( $p + 15 );
        $re.setRiskLevel( "medium low" );
end

rule "Even more risky surname"
    when
        Candidate( surname.hashCode() % 2 == 0 )
        $re : RiskEstimation ( $p : riskPoints )
        $log : Logger()
    then
    	$log.info("Even more risky surname");
        $re.setRiskPoints( $p + 10 );
        $re.setRiskLevel( "high" );  
end

rule "Very young candidate"
    when
        Candidate( age < 17 )
        $re : RiskEstimation ( $p : riskPoints )
        $log : Logger()
    then
    	$log.info("Very young candidate");
        $re.setRiskPoints( $p + 3 );
        $re.setRiskLevel( "medium" );
end


rule "Default"
    when
        Candidate()
        $re : RiskEstimation ( $p : riskPoints )
        $log : Logger()
    then
    	$log.info("Default: " + $re.hashCode() );
        $re.setRiskPoints( $p + 1 );
        $re.setRiskLevel( "low" );
        
        // debug
        $log.info( "RiskEstimation: " + $re );
        $log.info( "RiskEstimation: " + ObjectUtils.identityToString( $re ) );
end
